### ISSUE TITLE
Commit rights for cdelahousse

### ISSUE THREAD

**Issue by caniszczyk** [todogroup/repolinter#116]
@cdelahousse has been doing great work, I think he should be a full time committer :)

**Comment by caniszczyk** [comment]
If no one opposes in a couple of days, I will add Christian as a maintainer on the repo :)

**Comment by JoelMarcey** [comment]
@caniszczyk I am in 1000% percent in support of this 💯

**Comment by caniszczyk** [comment]
I didn't hear any objects so I added @cdelahousse to @todogroup/repolinter-maintainers 

Welcome and thanks for contributing :)
