### ISSUE TITLE
Option to exclude passing lines

### ISSUE THREAD

**Issue by trevmex** [todogroup/repolinter#122]
## Issue Report

If there are lots of lines in the report and most of them are passing, they can crowd out the errors.

## Expected Behavior

A command line option to exclude passing lines.

## Actual Behavior

No such option presently exists

## Steps to Reproduce the Issue

N/A

**Comment by prototypicalpro** [comment]
This is still an issue (for the CLI at least), but one modification that was made to help output readability was the addition of a markdown formatter in #174, which formats all the results in collapsable lists.
