### ISSUE TITLE
Optional summary report at the end of the run

### ISSUE THREAD

**Issue by trevmex** [todogroup/repolinter#123]
## Issue Report

I want a concise summary of errors and passing conditions at the bottom of the run, if optionally asked for.

## Expected Behavior

A command line option allows for a summary to appear at the bottom of the report.

## Actual Behavior

No option presently exists.

## Steps to Reproduce the Issue

N/A

**Comment by aculver28** [comment]
Hi @trevmex! Can you clarify exactly what you want to see in the summary? For example, are you looking for just pass/fail counts or something more/different?

**Comment by prototypicalpro** [comment]
This issue is pretty stale so I'm going to go ahead and close it. Please feel free to leave a comment if this problem is still relevant.
