### ISSUE TITLE
Add a rule for SECURITY_CONTACTS file

### ISSUE THREAD

**Issue by trevmex** [todogroup/repolinter#124]
## Issue Report

We should validate a SECURITY_CONTACTS file See https://github.com/kubernetes/kubernetes/blob/master/SECURITY_CONTACTS.

## Expected Behavior

We check to see if a repo has a SECURITY_CONTACTS file.

## Actual Behavior

We currently do not have this check.

## Steps to Reproduce the Issue

N/A

**Comment by caniszczyk** [comment]
This is basically replaced by SECURITY.md feature in github
