### ISSUE TITLE
Scan for PATENTS in files

### ISSUE THREAD

**Issue by trevmex** [todogroup/repolinter#125]
## Issue Report

The term "PATENTS" can trigger bad things for some users.

## Expected Behavior

Add a rule to detect the usage of the word "PATENTS" in the project.

## Actual Behavior

It does not do this right now.

## Steps to Reproduce the Issue

N/A

**Comment by prototypicalpro** [comment]
This check can be implemented using the `file-not-contents` rule:
```javascript
[
  {
    "file-no-patents": {
      "level": "error",
      "rule": {
        "type": "file-not-contents",
        "options": {
          "globsAll": "**/*",
          "content": "PATENTS"
        }
      }
    }
  }
]
```
As such, I believe this issue is resolved.
