### ISSUE TITLE
Add rule to check for NOTICE file

### ISSUE THREAD

**Issue by trevmex** [todogroup/repolinter#126]
## Issue Report

Add a rule to check for a NOTICE file.
See https://github.com/Comcast/petasos/blob/master/NOTICE for an example.

## Expected Behavior

There is a rule to check for the NOTICE file.

## Actual Behavior

There is no rule for this right now.

## Steps to Reproduce the Issue

N/A

**Comment by cdelahousse** [comment]
This already exists for Apache licenses, which seems to be the only case we'd want it.
https://github.com/todogroup/repolinter/blob/master/rulesets/default.json#L48-L49
https://github.com/todogroup/repolinter/blob/master/rules/apache-notice.json

**Comment by annania** [comment]
I think this can close, if users want it for all projects, they can edit the repolinter.json file and move the notice check to the all section.

**Comment by trevmex** [comment]
Closing, then. Thanks for the input!
