### ISSUE TITLE
Rename "rules" files to "modules"

### ISSUE THREAD

**Issue by cdelahousse** [todogroup/repolinter#131]
So, the way I see it, we have three levels of functionality that we can define:
1) Rulesets: sets of rules
2) Rules: applications of modules to create some type of test. Eg. file-existence applied to the 'readme.md' pattern creates the "Does this repo have a readme" rule (ie. "readme-file-exists:file-existence": ["error", {"files": ["README*"], "nocase": true}],)
3) Modules: query operations on the repo (eg. file-existence)

Currently, we've structured out code as
1) Rulesets: a series of rules
2) Rules and Modules: we use them interchangebly. We call the objects from the 'rules' folder in the result object "modules".  

I suggest we do the following:
* Rename the `rules` directory to `modules`
* Try to make this clearer in code

This will make the distinction between rules and 'modules' more clear.

**Comment by trevmex** [comment]
Sounds like an interesting idea, as long as we can do it in a backwards-compatable manner. I'd love to see a PR on this.

**Comment by prototypicalpro** [comment]
This is a good idea, but the issue is stale. Feel free to leave a comment if you would still like to see this happen.
