### ISSUE TITLE
Create a series of default rules instead of having them defined in rulesets/default.json

### ISSUE THREAD

**Issue by cdelahousse** [todogroup/repolinter#132]
As mentioned in #131 , I see repo linter as having 3 levels of functionality:
* Rulesets: sets of rules
* Rules: applications of modules to create some type of test. Eg. file-existence applied to the 'readme.md' pattern creates the "Does this repo have a readme" rule (ie. "readme-file-exists:file-existence": ["error", {"files": ["README*"], "nocase": true}],)
* Modules: query operations on the repo (eg. file-existence)

Currently, the only way to define default rules is within rulesets. I think it would be a good idea to decouple the rules from rules.

My idea: 

1) create a json file for every rule that defines a name(eg. 'readme-file-exists'), a module(eg 'file-existence'), and default params (eg. 
`{ "announce-level": 'error', "files": ["README*"], "nocase": true}`)
2) Refer to the rules by name in the rulesets/default.json (eg. a list [ 'readme-file-exists', 'support-file-exists', .... ]) instead of defining them in that file.

Why? It decouples the idea of rules and rulesets. It would let us reuse rules in different contexts.

**Comment by trevmex** [comment]
I'm down to see a PR for this, as long as it does not break backwards compatibility.

**Comment by prototypicalpro** [comment]
This issue is stale and I'm going to go ahead and close it. Feel free to leave a comment if you would still like to see this happen.
