### ISSUE TITLE
Rule test-directory-exists fails on remote repos but passes on local repos

### ISSUE THREAD

**Issue by DuaneOBrien** [todogroup/repolinter#142]
## Issue Report

When running repolinter against a remote directory, the "test-directory-exists" rule appears to always fail, even when it passes on a local clone of the repo.

## Expected Behavior

Results from local test:

```duaneo@MACHINE:~/Code/working/repolinter$ node bin/repolinter.js  .
Target directory: /home/duaneo/Code/working/repolinter
Ruleset: ../../../repolint.json
✔ test-directory-exists: found (node_modules/array-from/test.js)
```
## Actual Behavior

Results from remote test:

```duaneo@MACHINE:~/Code/working/repolinter$ node bin/repolinter.js  --git https://github.com/todogroup/repolinter
Target directory: /home/duaneo/Code/working/repolinter/tmp/23cb2e61-589e-418d-8368-911aabab5e5a
Ruleset: ../../../../../repolint.json
✖ test-directory-exists: not found: (**/test*, **/specs)
```

## Steps to Reproduce the Issue

repolint.json :

``{
  "axioms": {
    "linguist":"language",
    "licensee":"license",
    "packagers":"packager"
  },
  "rules": {
    "all": {
      "test-directory-exists:directory-existence": ["error", {"directories": ["**/test*", "**/specs"], "nocase": true}]
    }
  }
}``

OS: Ubuntu 18.04.2 LTS
node: v8.10
npx: 10.2.0
npm: 3.5.2
ruby: 2.5.1p57

**Comment by prototypicalpro** [comment]
I believe this was fixed in #174. Please leave a comment if this is not the case.
