### ISSUE TITLE
accidental push

### ISSUE THREAD

**Issue by willnorris** [todogroup/repolinter#194]
I pushed to the wrong remote.  Honestly didn't even realize I had permission on this one. :-\

Fixing it now.

**Comment by willnorris** [comment]
I'll try to poke through `git reflog` to see what the last commit master pointed to was, but it might be simpler for someoene else to look at your local check out to roll this back.  @prototypicalpro can you take a look?

**Comment by willnorris** [comment]
reflog isn't much help.  I can't easily tell how many commits I accidentally pushed us forward.  It looks like the bulk of these changes were in the process of getting merged as part of #192 anyway, so maybe we just leave things as-is, complete the review, and fix anything that needs changing from there?

**Comment by willnorris** [comment]
Ah, looking at the slack message, it seems that 4cfa12245dbd was the previous HEAD before this push.  That would be the rollback point if we want to do that.

**Comment by prototypicalpro** [comment]
No worries! It looks like other than the PR there wasn't any other made, so it should be fine (that PR was about ready to me merged anyway). All the tests are passing, so I think I'm just going to leave it.

**Comment by willnorris** [comment]
cool, thanks for confirming.
