### ISSUE TITLE
Move rule configuration to a JSON file

### ISSUE THREAD

**Issue by willbar** [todogroup/repolinter#2]
- [ ] Look for a standard filename up the current directory tree (e.g. repolint.json)
- [ ] Allow path to a rule configuration to be passed to the executable

**Comment by willbar** [comment]
I'm thinking we should adopt something similar to the ESLint format, based on our current rules it would look something like this:

```
{
  "rules": {
    "license-file-exists": ["error", {"files": ["LICENSE*", "COPYING*"]}],
    "readme-file-exists": ["error", {"files": ["README*"]}],
    "contributing-file-exists": ["error", {"files": ["CONTRIB*"]}],
    "readme-references-license": ["error", {"patterns": ["license"]}],
    "readme-references-code-of-conduct": ["error", {"patterns": ["code of conduct"]}],
    "binaries-not-present": ["error", {"extensions": ["*.exe", "*.dll"]}],
    "license-detactable-by-licensee": ["error"],
    "test-directory-exists": ["error", {"directories": ["test*", "specs"]}],
    "source-license-headers-exist": ["error", {"files": ["**/*.js"], "ignores": "node_modules/**", "lineCount": 5}]
  }
}
```

Thoughts?

**Comment by trevmex** [comment]
I think that is a good first go. Let's do it.

**Comment by trevmex** [comment]
let's put it in a config/ directory (eg. config/repolint.json)

**Comment by bkeepers** [comment]
I think that's a good start.

**Comment by willbar** [comment]
@trevmex most existing tools (grunt, eslint, jslint, tslint, etc.) don't use a subdirectory, I'll configure it to look both in the target directory as well as target directory/config so people have a choice.

**Comment by trevmex** [comment]
PR #17 addresses this.
