### ISSUE TITLE
Inherit a ruleset from another ruleset

### ISSUE THREAD

**Issue by iamwillbar** [todogroup/repolinter#21]
Today the only way to customize the rules is to copy the default ruleset and edit it... You should be able to create a ruleset that extends a ruleset and add new rules or change configuration on existing rules.

**Comment by hyandell** [comment]
Realizing that my reference was about making a rule extend another rule (ie: stop copy and paste between rules); whereas this is about cascading rulesets themselves.

**Comment by willnorris** [comment]
I'm particularly interested in seeing this implemented for use here at Twitter.  Would this not be as simple as a new "extends" field in the ruleset, and then recursively deep merging the sets?  A child ruleset could override a rule from a parent by setting `level: off`.

I, or someone on my team, may take a look at providing a PR for this, I just wanted to make sure I wasn't missing anything.

**Comment by willnorris** [comment]
Actually, that might not work if you're wanting to, for example, remove a value from an options array .  By default, I suspect it would combine the arrays.  Maybe a shallow merge then of just the top-level rules?  That would still result in some duplicating if you're just wanting to change the configuration of an existing rule, but makes it trivial to add new rules, and is still better than what we have today.

**Comment by iamwillbar** [comment]
Your suggestion is the direction I would have gone, don't think you're missing anything significant there.

**Comment by prototypicalpro** [comment]
I think #207 should've closed this, so I'll go ahead and do that.
