### ISSUE TITLE
Make a logo

### ISSUE THREAD

**Issue by trevmex** [todogroup/repolinter#23]
I am going to go on fiverr and get a logo commissioned.

**Comment by trevmex** [comment]
I'm going to commission [Ei8htz](https://www.fiverr.com/ei8htz/design-2-outstanding-logo) and see if we can tie in the [TODO color pallete](http://todogroup.org/).

**Comment by trevmex** [comment]
Order is [in progress](https://www.fiverr.com/users/trevmex/orders/FO299CB200D5).

**Comment by trevmex** [comment]
![](http://i.imgur.com/Is612vV.jpg)

We get one revision, but I am pretty happy with it.

If you have a revision, you have to let me know within two days from now.

**Comment by trevmex** [comment]
![p_repolinter01](https://user-images.githubusercontent.com/73104/27294619-097e61aa-54cf-11e7-8a62-e92d9c6471b7.png)

Here is another one they made. We can choose between the two.

**Comment by caniszczyk** [comment]
I'm fine with both, maybe lean towards the second one!

Thanks for doing this work @trevmex! Next time, just to let you know you can have access to the Linux Foundation Design team to prototype designs / a logo, it's one of the benefits of being part of the LF family!

**Comment by trevmex** [comment]
Thanks for the heads up! I am leaning towards the second one, too!
