### ISSUE TITLE
Make a github site

### ISSUE THREAD

**Issue by trevmex** [todogroup/repolinter#24]
We should have a github site to highlight the tool.

**Comment by trevmex** [comment]
I used the TODO Group page as a template for a starter repo linter page. Now we just need to figure out how to get the master/docs page here linked to todogroup.org/repolinter.

**Comment by trevmex** [comment]
This is what it looks like to me: https://trevmex.github.io/repolinter/

**Comment by hyandell** [comment]
Need to have Admin on this repo, then flip the option for publishing a site.

**Comment by trevmex** [comment]
@caniszczyk Can you help make https://trevmex.github.io/repolinter/ a reality here?

**Comment by caniszczyk** [comment]
@trevmex just put what you want in the docs/ folder, that gets rendered to http://todogroup.org/repolinter/

**Comment by trevmex** [comment]
Thanks, @caniszczyk!
