### ISSUE TITLE
Site to run repolinter

### ISSUE THREAD

**Issue by trevmex** [todogroup/repolinter#26]
It would be nice to have a site where we can input a URL and get an HTML report, using repolinter as the backend.

**Comment by jwsloan** [comment]
I was just considering contributing a Dockerfile that would follow [these directions](https://developer.github.com/v3/guides/building-a-ci-server/) to spin up a small repolinter ci server, which could be deployed to heroku or wherever. It wouldn't do exactly what you're talking about, but I think it would be handy. What do you think, @trevmex?

**Comment by jwsloan** [comment]
Sounds good, @trevmex. I've already submitted a new [CodeClimate Engine](https://github.com/jwsloan/codeclimate-repolinter) that enables repolinter in CodeClimate. I could pull a modified version of that Dockerfile back into this project.

**Comment by hyandell** [comment]
I wonder if it would be better to link from the readme over to your CodeClimate Engine repo. Keep things decoupled etc.

Also wondering if we should have a separate repolinter-ci-server repository that follows the directions you link to, and a repolinter-web-ui for @trevmex's original idea.

**Comment by jwsloan** [comment]
@hyandell - That may be the case. I'd say we wait for CodeClimate to accept the engine before doing that, though. I've only recently submitted it, and have not heard from them yet.

**Comment by hyandell** [comment]
Note that we (OSPO I work with) have made a dashboard for repolinter:

  https://github.com/amzn/dashboard-for-repolinter

I'm going to propose moving that repo over to be a sibling of this one.

Closing this as I think the original request is covered by https://github.com/amzn/dashboard-for-repolinter bar one running on the public internet which is a bigger question.
