### ISSUE TITLE
Get licensee and linguist working under Windows

### ISSUE THREAD

**Issue by trevmex** [todogroup/repolinter#33]
After much work, I was able to get linguist and licensee to gem install on RailsInstaller in Windows 10, but the commandline executables are not made for cmd or PowerShell.

**Comment by sschuberth** [comment]
Wouldn't these be more bugs for the upstream projects at https://github.com/benbalter/licensee and https://github.com/github/linguist, respectively? In any case, `gem install licensee` and running `licensee` works just fine for me out of the box on Windows 10 (using https://github.com/oneclick/rubyinstaller2 and Git Bash from https://github.com/git-for-windows/git).

**Comment by sschuberth** [comment]
BTW, not being able to install linguist on Windows is tracked at https://github.com/github/linguist/issues/3649. @trevmex, can you share in that ticket how you made linguist build on Windows?

**Comment by trevmex** [comment]
I can't say I got it working, per se, just compiling. It was...messy to say the least.
