### ISSUE TITLE
Don't output absolute filenames

### ISSUE THREAD

**Issue by hyandell** [todogroup/repolinter#44]
Currently the output includes absolute filenames. This looks odd when reports are published. For example:

Target directory: /Users/hyandell/oss/repolinter
Ruleset: /Users/hyandell/oss/repolinter/rulesets/default.json
Languages: ruby, batchfile, javascript

✔ readme-references-license: File /Users/hyandell/oss/repolinter/README.md contains license

Would be better for this to be independent of where I ran it. ie It should say:

Target directory: .
Ruleset: rulesets/default.json
Languages: ruby, batchfile, javascript

✔ readme-references-license: File ./README.md contains license

**Comment by trevmex** [comment]
Looks like this is already working with the exception of the Target directory, and I think that we should keep that one (and only that one) absolute.

I've had too many bugs where I don't know what . means when running a command. :P
