### ISSUE TITLE
use APIs to get individual files instead of cloning

### ISSUE THREAD

**Issue by bufferoverflow** [todogroup/repolinter#54]
Using repolinter on a large amount of repos does not scale as git clone is required for each repo.

Would be great to use the APIs of GitHub and GitLab for those individual checks:
* https://developer.github.com/v3/repos/contents
* https://gitlab.com/help/api/repository_files.md

**Comment by hyandell** [comment]
(speaking just myself) Given, at least for GitHub, the limitation on API calls (and search API calls have their own limits); I prefer to run it locally. I think I'm saying disk space is cheaper than GitHub API tokens :)

**Comment by bufferoverflow** [comment]
Yes, disk space is cheap. However, running repolinter across a large amount of repos with git clone for each one does not scale that nice. Anyway, I come back with a PR as soon as the pain is big enough, 😄 .

**Comment by hyandell** [comment]
Sounds good :) I've the same potential pain with https://github.com/amzn/oss-dashboard - it clones every repo. I've had more pain with the lack of github tokens to sync data and the cpu cost of running a ruby grep across the files when there are lots of hits. One of my 2018 goals is to hook up repolinter so it runs on them all.

**Comment by hyandell** [comment]
One of the features of https://github.com/amzn/dashboard-for-repolinter is/will be hooking it up to an org:hook and running repolinter on each event. It still git clones which is cheaper than running lots of GitHub API calls (from a 5,000 API calls an hour is not very much). 

Codewise I think the best way to do this (use GitHub API not clone) is to inject a layer beneath the rules for 'get file list', 'search files' etc.

**Comment by jwsloan** [comment]
@hyandell I'm planning on creating an app on the [probot](https://probot.github.io/) framework that wraps `repolinter`. I think that would be a better route than baking it directly into your dashboard. That would allow people to get the github hook functionality without also having to use the dashboard. How do you feel about that?

**Comment by bkeepers** [comment]
@jwsloan I was just thinking about that recently. I would _love_ to see a probot app that offers this functionality. Let me know how I can help.

**Comment by prototypicalpro** [comment]
At New Relic we solved this issue by requiring [repolinter-action](https://github.com/newrelic/repolinter-action) to be installed on every repository, and allowing each team to manage the workflow themselves. Since this issue it pretty stale I'm going to go ahead and close it, if anyone still feels this problem is relevant feel free to comment and I can re-open it.
