### ISSUE TITLE
Conditional rules? Rule dependencies?

### ISSUE THREAD

**Issue by hyandell** [todogroup/repolinter#59]
The initial use case is:

If license is Apache 2.0, then check if NOTICE file is there.

It's similar to Linguist/language support in principle. If <axiom is A>, then <rule B>. 

I think it means running a series of Axioms, and then having rules that are dependent on the Axiom's output. So 'If language=Java' is the axiom, and "Java rule set" is the output.

**Comment by hyandell** [comment]
I've implemented this. Linguist and Licensee move into an axioms/ directory. index.js changes to execute axioms, then base its rule targets on the outputted axioms.

Ideally rules would also have access to the output from the axioms so that the license-detectable-by-licensee rule wouldn't have to re-execute licensee but could simply look at the output. Will work on a PR (need to learn how to have multiple PRs in play at once :) )

**Comment by jwsloan** [comment]
@hyandell you can create multiple branches in your fork of the project, and create PRs from each of them.

**Comment by hyandell** [comment]
Thanks @jwsloan - added as PR #66

**Comment by hyandell** [comment]
The PR was merged :)
