### ISSUE TITLE
Check NOTICE file exists if Apache 2.0

### ISSUE THREAD

**Issue by hyandell** [todogroup/repolinter#65]
Proposed code. Would be much simpler with a solution for #59. Alternatively, could have a system similar to the linguist plugins where the core code identifies the license, and then rules are run per license. 

```
// Copyright 2018 TODO Group. All rights reserved.
// Licensed under the Apache License, Version 2.0.

const isWindows = require('is-windows')
const spawnSync = require('child_process').spawnSync
const Result = require('../lib/result')

// TODO: In an ideal world this rule would depend on, and obtain the reuslts of, the licensee rule; and it would then simply be an invocation of the file-exists rule
module.exports = function (fileSystem, rule) {
  const expected = /License: ([^\n]+)/

  const licenseeOutput = spawnSync(isWindows() ? 'licensee.bat' : 'licensee', [fileSystem.targetDir]).stdout

  let result = new Result(rule, '', null, false)
  if (licenseeOutput == null) {
    result.message = 'Licensee is not installed'
    return [result]
  }

  const license = licenseeOutput.toString().match(expected)

  if (license != null && license[1] == 'Apache License 2.0') {

    const options = rule.options
    const fs = options.fs || fileSystem
    noticeFiles = ['NOTICE', 'NOTICE.md', 'NOTICE.txt']
    const file = fs.findFirst(noticeFiles)

    result.passed = !!file
    if(!!file) {
      result.message = `found (${file})`
    } else {
      result.message = `not found: (${noticeFiles.join(', ')})`
    }

  } else {
    result.message = 'Licensee did not identify this project as Apache 2.0 licensed'
  }

  return [result]
}

```

**Comment by hyandell** [comment]
Or I could ditch this in favour of the axiom approach in #59 where implementing this becomes the svelte:

    "license=Apache License 2.0": {
      "notice-file-exists:file-existence": ["error", {"files": ["NOTICE*"]}]
    }

**Comment by bufferoverflow** [comment]
I like that idea and would suggest to use the SPDX identifier as key.
Take care, `NOTICE` file is optional, see https://github.com/todogroup/repolinter/blob/master/LICENSE#L106

**Comment by hyandell** [comment]
Agreed, but then so is a CONTRIBUTING file or CODE_OF_CONDUCT. A NOTICE file is definitely recommended (Apache require it on every one of their projects).

**Comment by hyandell** [comment]
Axiom approach implemented in #66. It uses the output from licensee; but that's the SPDX identified afaik so indirectly following @bufferoverflow's suggestion :)

**Comment by trevmex** [comment]
Just merged the axiom with notice. I'll add a PR to add a NOTICE file to repolinter so we don't fail ourselves.

**Comment by hyandell** [comment]
Thanks :) Just merged it. Closing this.
