### ISSUE TITLE
Enhance the docs/ site with details on Repo Linter

### ISSUE THREAD

**Issue by trevmex** [todogroup/repolinter#79]
The todogroup.org/repolinter site is pretty barebones right now. Let's enhance it with details on how to use repolinter, why it is important, and when to use it!

**Comment by hyandell** [comment]
Site:  http://todogroup.org/repolinter/
Source: https://github.com/todogroup/repolinter/tree/master/docs

**Comment by hyandell** [comment]
Doc site currently broken. GitHub states that it's generating the site but you can't get to it, presumably an issue with url rewriting from the higher todogroup site?

**Comment by prototypicalpro** [comment]
The barebones site was replaced with autogenerated documentation in #174, viewable [here](https://todogroup.github.io/repolinter/).
