### ISSUE TITLE
Enhance Licensee (or other engine) Integration

### ISSUE THREAD

**Issue by craigez** [todogroup/repolinter#80]
Licensee is a little touchy and sensitive to small changes in licenses, I'd like to be able to use repolinter to verify expected licenses on a project. I have a couple changes in this direction (e.g. specifying a threshold for matching) I need to clean up to submit.

**Comment by hyandell** [comment]
Something I have as a patch to licensee that needs more work is a custom source of licenses for licensee (ie: let's you add more to the default list). Not sure if that would help your use case here. It's currently a monkey patch to github.com/amzn/oss-dashboard

**Comment by craigez** [comment]
That would help, as we could add our standard markings.

**Comment by hyandell** [comment]
Nudge just to see if you were still interested in providing this contribution?

**Comment by craigez** [comment]
Sorry, this had dropped off my radar. By the time I was able to go back and look at licensee a lot of changes and my patches were not useful anymore. Assuming this is the patch you are referring to: https://github.com/amzn/oss-dashboard/blob/master/license-monkey.rb

**Comment by hyandell** [comment]
From f2f chat features Craig was thinking of:

* The monkey patch above so that licensee has an additional license database.
* Pass along parameters to licensee so you can configure how it manages things.

**Comment by prototypicalpro** [comment]
As this issue is two years old I'm going to go ahead and close it, feel free to re-open it if Licensee is still having issues.
