### ISSUE TITLE
use SPDX license identifiers

### ISSUE THREAD

**Issue by jeffmcaffer** [todogroup/repolinter#82]
The awesome new license axiom support appears to use the `licensee` license names rather than SPDX identifiers. Let's settle on using SPDX identifiers as much as possible.

**Comment by hyandell** [comment]
Need to get Licensee offering SPDX identifiers first. Here's the output on repolinter:

I think it relates to this Licensee issue: https://github.com/benbalter/licensee/issues/267

**Comment by hyandell** [comment]
Licensee is now on SPDX Identifiers, which should resolve this.
