### ISSUE TITLE
New Rule: .github/TEMPLATES.md

### ISSUE THREAD

**Issue by decause** [todogroup/repolinter#83]
Issue and Pull Request Templates are a great way to help improve the quality of contributions, and reduce the overhead of triaging issues. see: https://github.com/blog/2111-issue-and-pull-request-templates

<code>README.md</code> would look something like:

## github-templates-exist
Fails if there isn't a directory matching <code>.github</code> or <code>ISSUE_TEMPLATE.md</code> <code>PULL_REQUEST_TEMPLATE.md</code> in the directory tree of the target directory.

**Comment by caabernathy** [comment]
I can take this one.

**Comment by caabernathy** [comment]
Done and merged.
