### ISSUE TITLE
repolinter should only consider files versionned in git if a .git directory is present

### ISSUE THREAD

**Issue by Lucas-C** [todogroup/repolinter#99]
When I run `repolinter` on https://github.com/voyages-sncf-technologies/vboard this is part of the output I get:
```
× binaries-not-present: Excluded file type exists (vboard-front/node_modules/gifsicle/vendor/gifsicle.exe)
× binaries-not-present: Excluded file type exists (vboard-front/node_modules/jpegtran-bin/vendor/jpegtran.exe)
× binaries-not-present: Excluded file type exists (vboard-front/node_modules/optipng-bin/vendor/optipng.exe)
× binaries-not-present: Excluded file type exists (vboard-front/node_modules/phantomjs/lib/phantom/phantomjs.exe)
× binaries-not-present: Excluded file type exists (vboard-front/node_modules/jpegtran-bin/vendor/libjpeg-62.dll)
× license-detectable-by-licensee: Licensee is not installed
√ test-directory-exists: found (repolinter/tests)
√ integrates-with-ci: found (.travis.yml)
‼ source-license-headers-exist: EMFILE: too many open files
```

I have a feature request : could only the versionned files be parsed by `repolinter` when used in a `git` repository, to avoid those false positives and this final application crash ?

**Comment by hyandell** [comment]
I think this is a third form of 'get file' option. We have an existing request to use GitHub APIs rather than local file. This is a request to use git command line as the API rather than file system. Ideally all would be behind a single API (ie: file_system.js ?).

**Comment by trevmex** [comment]
Interesting idea. I think it makes sense to do this if the .git/ directory is present _and_ git is installed on the executing machine, otherwise have it fall back to the default behavior. I agree, having it behind one API seems ideal.

**Comment by prototypicalpro** [comment]
At the moment the "working tree" check is implemented using the `git` command line, which if I'm understanding the issue correctly addresses the problem.
